before:
  hooks:
    - helm package ./helm/ --version {{ .Version }} --app-version v{{ .Version }}
builds:
  - skip: true
    main: ./main.go
    ldflags:
      - -s -w -X github.com/bakito/k8s-event-logger-operator/version.Version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  extra_files:
    - glob: ./k8s-event-logger-operator-*.tgz
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
