language: go
go:
  - 1.13.x
os:
  - linux
dist: trusty
sudo: false
install: true

env:
  - GO111MODULE=on


before_script:
  - curl -L https://github.com/operator-framework/operator-sdk/releases/download/v0.14.0/operator-sdk-v0.14.0-x86_64-linux-gnu --output operator-sdk
  - chmod +x operator-sdk
  - export PATH=$PATH:/$(pwd)

script:
  - go test -coverprofile=coverage.out  ./...
  - go tool cover -func=coverage.out
  - go build ./...
  - operator-sdk generate crds
  - operator-sdk generate k8s
