language: generic

services:
  - docker

script:
  - docker build -t quay.io/bakito/k8s-event-logger-operator:$TRAVIS_BRANCH -f build/operator.Dockerfile .
  - docker build -t quay.io/bakito/k8s-event-logger:$TRAVIS_BRANCH          -f build/logger.Dockerfile   .

