language: go
go:
  - 1.13.x
os:
  - linux

services:
  - docker
before_script:
  - go get github.com/mattn/goveralls
script:
  - go test ./...  -coverprofile=coverage.out
  - goveralls -service=travis-ci -v -coverprofile=coverage.out
  - docker build -t quay.io/bakito/k8s-event-logger:$TRAVIS_BRANCH -f build/Dockerfile .

deploy:
  - provider: script
    script: build/push-to-quay.sh quay.io/bakito/k8s-event-logger
    on:
      branch: "master"
  - provider: script
    script: build/push-to-quay.sh quay.io/bakito/k8s-event-logger
    on:
      tags: true
