apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-event-logger-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "k8s-event-logger-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "k8s-event-logger-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "k8s-event-logger-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "k8s-event-logger-operator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/go/k8s-event-logger
          args:
            - "--enable-leader-election={{ .Values.eventLogger.leaderElection }}"
          env:
            - name: OPERATOR_NAME
              value: {{ include "k8s-event-logger-operator.fullname" . }}
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: LOGGER_POD_REQUEST_CPU
              value: "{{ .Values.eventLogger.resources.requests.cpu }}"
            - name: LOGGER_POD_REQUEST_MEM
              value: "{{ .Values.eventLogger.resources.requests.memory }}"
            - name: LOGGER_POD_LIMIT_CPU
              value: "{{ .Values.eventLogger.resources.limits.cpu }}"
            - name: LOGGER_POD_LIMIT_MEM
              value: "{{ .Values.eventLogger.resources.limits.memory }}"
            - name: "ENABLE_WEBHOOKS"
              value: "{{ .Values.webhook.enabled }}"
            {{- if .Values.eventLogger.leaderElectionResourceLock }}
            - name: EnvLeaderElectionResourceLock
              value: .Values.eventLogger.leaderElectionResourceLock
            {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: metrics
            {{- if .Values.webhook.enabled }}
            - containerPort: 9443
              name: webhook
          {{- end }}
          {{- if .Values.webhook.enabled  }}
          volumeMounts:
            - mountPath: /opt/go/certs
              name: "webhook-certs"
              readOnly: true
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.webhook.enabled }}
      volumes:
        - name: "webhook-certs"
          secret:
            defaultMode: 420
            secretName: {{ include "k8s-event-logger-operator.webhookCertSecretName" . }}
      {{- end }}
