apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-event-logger-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "k8s-event-logger-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
  {{- include "k8s-event-logger-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "k8s-event-logger-operator.selectorLabels" . | nindent 8 }}
      {{- with .Values.extraPodLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.extraPodAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-event-logger-operator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /opt/go/k8s-event-logger
          args:
            - '--enable-leader-election={{ .Values.eventLogger.leaderElection }}'
          env:
            - name: OPERATOR_NAME
              value: {{ include "k8s-event-logger-operator.fullname" . }}
            - name: 'WATCH_NAMESPACE'
              value: ''
            - name: 'POD_NAME'
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: 'POD_NAMESPACE'
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: 'CONFIG_MAP_NAME'
              value: '{{ include "k8s-event-logger-operator.fullname" . }}'
            - name: 'ENABLE_WEBHOOKS'
              value: '{{ .Values.webhook.enabled }}'
            {{- if .Values.eventLogger.leaderElectionResourceLock }}
            - name: LEADER_ELECTION_RESOURCE_LOCK
              value: {{ .Values.eventLogger.leaderElectionResourceLock }}
            {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: metrics
            {{- if .Values.webhook.enabled }}
            - containerPort: 9443
              name: webhook
          {{- end }}
          {{- if .Values.webhook.enabled  }}
          volumeMounts:
            - mountPath: /opt/go/certs
              name: 'webhook-certs'
              readOnly: true
          {{- end }}
         {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.webhook.enabled }}
      volumes:
        - name: 'webhook-certs'
          secret:
            defaultMode: 420
            secretName: {{ include "k8s-event-logger-operator.webhookCertSecretName" . }}
      {{- end }}
