{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-event-logger-operator.serviceAccountName" . }}
  labels:
{{ include "k8s-event-logger-operator.labels" . | nindent 4 }}
{{- end -}}
