apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-event-logger-operator.fullname" . }}
  labels:
  {{- include "k8s-event-logger-operator.labels" . | nindent 4 }}
  {{- if .Values.webhook.openShiftServiceCert.enabled }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "k8s-event-logger-operator.webhookCertSecretName" . }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    {{- if .Values.webhook.enabled }}
    - name: webhook
      port: 443
      targetPort: webhook
    {{- end }}
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: metrics
  selector:
    {{- include "k8s-event-logger-operator.selectorLabels" . | nindent 6 }}
