
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-eventlogger-bakito-ch-v1-eventlogger
  failurePolicy: Fail
  name: meventlogger.kb.io
  rules:
  - apiGroups:
    - eventlogger.bakito.ch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eventloggers

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-eventlogger-bakito-ch-v1-eventlogger
  failurePolicy: Fail
  name: veventlogger.kb.io
  rules:
  - apiGroups:
    - eventlogger.bakito.ch
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - eventloggers
