# permissions for end users to view eventloggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventlogger-viewer-role
rules:
- apiGroups:
  - eventlogger.bakito.ch
  resources:
  - eventloggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eventlogger.bakito.ch
  resources:
  - eventloggers/status
  verbs:
  - get
