# permissions for end users to edit eventloggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventlogger-editor-role
rules:
- apiGroups:
  - eventlogger.bakito.ch
  resources:
  - eventloggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventlogger.bakito.ch
  resources:
  - eventloggers/status
  verbs:
  - get
