# permissions for end users to view pods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-viewer-role
rules:
- apiGroups:
  - eventlogger.bakito.ch
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - eventlogger.bakito.ch
  resources:
  - pods/status
  verbs:
  - get
