apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventloggers.eventlogger.bakito.ch
spec:
  group: eventlogger.bakito.ch
  names:
    kind: EventLogger
    listKind: EventLoggerList
    plural: eventloggers
    singular: eventlogger
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: EventLogger is the Schema for the eventloggers API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EventLoggerSpec defines the desired state of EventLogger
          properties:
            annotations:
              additionalProperties:
                type: string
              description: Labels additional annotations for the logger pod
              type: object
            eventTypes:
              description: EventTypes the event types to log. If empty all events
                are logged.
              items:
                type: string
              minItems: 0
              type: array
            kinds:
              description: Kinds the kinds to logg the events for
              items:
                description: Kind defines a kind to loge events for
                properties:
                  eventTypes:
                    description: EventTypes the event types to log. If empty events
                      are logged as defined in spec.
                    items:
                      type: string
                    minItems: 0
                    type: array
                  matchingPatterns:
                    description: MatchingPatterns optional regex pattern that must
                      be contained in the message to be logged
                    items:
                      type: string
                    minItems: 0
                    type: array
                  name:
                    minLength: 3
                    type: string
                  skipOnMatch:
                    description: SkipOnMatch skip the entry if matched
                    type: boolean
                required:
                - name
                type: object
              minItems: 1
              type: array
            labels:
              additionalProperties:
                type: string
              description: Labels additional labels for the logger pod
              type: object
            namespace:
              description: Namespace the namespace to watch on, may be an empty string
              nullable: true
              type: string
            scrapeMetrics:
              description: ScrapeMetrics if true, prometheus scrape annotations are
                added to the pod
              type: boolean
            serviceAccount:
              description: ServiceAccount the service account to use for the logger
                pod
              type: string
          type: object
        status:
          description: EventLoggerStatus defines the observed state of EventLogger
          properties:
            error:
              description: Error
              type: string
            lastProcessed:
              description: LastProcessed the timestamp the cr was last processed
              format: date-time
              type: string
            operatorVersion:
              description: OperatorVersion the version of the operator that processed
                the cr
              type: string
          required:
          - lastProcessed
          - operatorVersion
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
