apiVersion: v2
name: k8s-event-logger-operator
description: This operator creates a logging pod that logs corev1.Event information as structured json log. The crd allows to configure the events to be logged.
type: application
version: "1.10.2"
appVersion: "v1.10.2"
