# Default values for k8s-event-logger-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  # --  Repository to use
  repository: ghcr.io/bakito/k8s-event-logger
  # -- Image pull policy
  pullPolicy: IfNotPresent

eventLogger:
  # --  Enable leader election for the controller
  leaderElection: true
  # --  Leader election lock type
  leaderElectionResourceLock:
  # -- Resource limits and requests for the operator pods.
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

logging: # see https://github.com/operator-framework/operator-sdk/blob/master/doc/user/logging.md
  # -- Log level
  level: info
  # -- Log time encoding
  timeEncoding: iso8601

webhook:
  # -- Specifies whether validation webhook should be created.
  enabled: false

  certManager:
    # -- Enable cert manager setup
    enabled: false

  openShiftServiceCert:
    # -- Enable OpenShift service certificate
    enabled: false
  certsSecret:
    # -- Certificate secret name
    name:
  # -- certificate ca bundle
  caBundle: Cg==

# -- String to partially override "argo-rollouts.fullname" template
nameOverride: ""

# -- String to fully override "argo-rollouts.fullname" template
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

rbac:
  # -- Specifies whether rbac should be created
  create: true
  # -- The name of the role and clusterrole to use.
  # If not set and create is true, a name is generated using the fullname template
  roleName:

# -- Resource limits and requests for the operator pods.
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi

# -- [Node selector]
nodeSelector: { }

# -- [Tolerations] for use with node taints
tolerations: [ ]

# -- Assign custom [affinity] rules to the deployment
affinity: { }
