apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventloggers.eventlogger.bakito.ch
spec:
  group: eventlogger.bakito.ch
  names:
    kind: EventLogger
    listKind: EventLoggerList
    plural: eventloggers
    singular: eventlogger
  scope: Namespaced
  subresources:
    status: {}

  version: v1
  versions:
    - name: v1
      served: true
      storage: true
