name: e2e tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install kind with registry
        uses: bakito/kind-with-registry-action@main

      - name: Build image
        run: ./testdata/e2e/buildImage.sh

      - name: Install helm chart
        run: |
          ./testdata/e2e/installChart.sh

      - name: Setup an EventLogger
        run: |
          kubectl apply -f testdata/e2e/test-eventlogger.yaml
          kubectl wait --namespace e2e-test \
            --for=condition=ready pod \
            --selector=app=event-logger-example-eventlogger \
            --timeout=90s

      - name: Start/Stop test pod
        run: |
          kubectl apply -f testdata/e2e/test-pod.yaml
          kubectl wait --namespace e2e-test --for=condition=ready pod nginx --timeout=90s
          kubectl delete -f testdata/e2e/test-pod.yaml

      - name: Check logs
        run: |
          kubectl logs -n e2e-test -l app=event-logger-example-eventlogger | grep '"logger":"event"'

      - name: Print logs
        run: |
          echo 'Pod logs' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          kubectl logs -n e2e-test -l app=event-logger-example-eventlogger >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
