name: end-2-end Helm Chart Tests

on:
  push:
    branches:
      - main
      - security-context
  pull_request:
    branches:
      - main

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install jq
        uses: dcarbone/install-jq-action@v1.0.1
      - name: Install yq
        uses: dcarbone/install-yq-action@v1.0.1

      - name: Set up Registry Container
        run: |
          docker run -d --restart=always -p "127.0.0.1:5001:5000" --name kind-registry registry:2

      - name: Build image
        run: ./testdata/e2e/buildImage.sh

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: v0.14.0
          kubectl_version: v1.24.0
          config: testdata/e2e/kind/config.yaml
      - name: Set up Local Registry
        run: |
          # https://kind.sigs.k8s.io/docs/user/local-registry/
          docker network connect kind kind-registry
          kubectl apply -f testdata/e2e/kind/configmap-registry.yaml
          # image registry: localhost:5001/

      - name: Install sealed-secrets-web with json format and cert URL
        run: |
          ./testdata/e2e/installChart.sh
