name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: make test

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

    - name: Test GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: --skip-publish --snapshot --rm-dist

    - name: Lint Helm Chart
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm lint helm/

    - name: Build
      run: go build -v ./...

