name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          skip-pkg-cache: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Test
        run: make test-ci

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out

      - name: Test GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: --skip-publish --snapshot --rm-dist
  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Lint
        run: |
          cp helm/README.md helm/README.md.old
          make helm-lint

      - name: Check chart/README.md is correctly generated with 'make docs'
        run: |
          # ignore version as it is updated during build
          sed -i '/!\[Version\:/d' helm/README.md
          sed -i '/!\[Version\:/d' helm/README.md.old
          diff helm/README.md.old helm/README.md

